SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `Compumaster` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

USE `Compumaster`;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `Nome` VARCHAR(255) NULL DEFAULT NULL ,
  `Senha` VARCHAR(255) NULL DEFAULT NULL ,
  `Tipo` VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `Nome_Aluno` VARCHAR(255) NULL DEFAULT NULL ,
  `Data_de_Nascimento` DATE NULL DEFAULT NULL ,
  `Nome_Responsavel` VARCHAR(255) NULL DEFAULT NULL ,
  `RG` VARCHAR(255) NULL DEFAULT NULL ,
  `CPF_CNPJ` VARCHAR(255) NULL DEFAULT NULL ,
  `Fone_1` VARCHAR(255) NULL DEFAULT NULL ,
  `Fone_2` VARCHAR(255) NULL DEFAULT NULL ,
  `Email` VARCHAR(255) NULL DEFAULT NULL ,
  `Endereco` VARCHAR(255) NULL DEFAULT NULL ,
  `Numero` VARCHAR(255) NULL DEFAULT NULL ,
  `Bairro` VARCHAR(255) NULL DEFAULT NULL ,
  `Cidade` VARCHAR(255) NULL DEFAULT NULL ,
  `Estado` VARCHAR(255) NULL DEFAULT NULL ,
  `Obs` BLOB NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Parcela` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `Data_de_Vencimento` DATE NULL DEFAULT NULL ,
  `Data_de_Pagamento` DATE NULL DEFAULT NULL ,
  `Valor_Pago` DOUBLE NULL DEFAULT NULL ,
  `idMatricula` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_matricula_parcela_idx` (`idMatricula` ASC) ,
  CONSTRAINT `fk_matricula_parcela`
    FOREIGN KEY (`idMatricula` )
    REFERENCES `Compumaster`.`Matricula` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Turma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `Dia_da_semana` VARCHAR(255) NULL DEFAULT NULL ,
  `Horario` VARCHAR(255) NULL DEFAULT NULL ,
  `Curso` VARCHAR(255) NULL DEFAULT NULL ,
  `Status` VARCHAR(255) NULL DEFAULT NULL ,
  `Data_Inicio` DATE NULL DEFAULT NULL ,
  `Data_Termino` DATE NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Chamada` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `Data` DATE NULL DEFAULT NULL ,
  `idAluno` INT(11) NULL DEFAULT NULL ,
  `idTurma` INT(11) NULL DEFAULT NULL ,
  `Obs` BLOB NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `aluno_chamada_idx` (`idAluno` ASC) ,
  CONSTRAINT `aluno_chamada`
    FOREIGN KEY (`idAluno` )
    REFERENCES `Compumaster`.`Aluno` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `turma_chamada`
    FOREIGN KEY (`idTurma` )
    REFERENCES `Compumaster`.`Turma` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `Compumaster`.`Matricula` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `idAluno` INT(11) NULL DEFAULT NULL ,
  `idTurma` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `aluno_idx` (`idAluno` ASC) ,
  INDEX `turma_idx` (`idTurma` ASC) ,
  CONSTRAINT `aluno`
    FOREIGN KEY (`idAluno` )
    REFERENCES `Compumaster`.`Aluno` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `turma`
    FOREIGN KEY (`idTurma` )
    REFERENCES `Compumaster`.`Turma` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
